version: '3.8'

services:
  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: ktrust-mongo
    hostname: ktrust-mongo.local
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ../data:/data/db
  nginx:
    image: nginx:latest
    container_name: ktrust-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    