version: '3.8'

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:18
    container_name: server-container
    hostname: server.local
    command: sleep infinity

  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: ktrust-mongo
    hostname: ktrust-mongo.local
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ../data:/data/db